WIP Blending
We are trying to get the blending right so that they blur together and not just overlap. Here is the current error with the code:
Traceback (most recent call last):
  File "c:\Users\ccouc\Documents\Github\CS473-ComputerVisionClass\HW_3\panorama.py", line 418, in <module>
    main()
  File "c:\Users\ccouc\Documents\Github\CS473-ComputerVisionClass\HW_3\panorama.py", line 389, in main
    panorama = blendImages(im1_expanded, im2_transformed)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ccouc\Documents\Github\CS473-ComputerVisionClass\HW_3\panorama.py", line 337, in blendImages
    img1 = cv2.multiply(img1, ramp_reshaped)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\arithm.cpp:650: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'cv::arithm_op'